INSERT INTO OYJR_RZHX.TONGANGE_USERTYPE8 (USER_ID, USER_TYPE_NAME) VALUES ('402880ea56ff918f0156ff91b1b10000', '群众');
INSERT INTO OYJR_RZHX.TONGANGE_USERTYPE8 (USER_ID, USER_TYPE_NAME) VALUES ('3', '党员');
INSERT INTO OYJR_RZHX.TONGANGE_USERTYPE8 (USER_ID, USER_TYPE_NAME) VALUES ('2', '团员');